# Generated by Django 4.0.3 on 2022-03-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_supers_powers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='powers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supers.power'),
        ),
    ]
